FROM python:3.12-slim

# 라이브러리 설치
WORKDIR /lib
COPY open_kknaks ./open_kknaks
COPY pyproject.toml .
RUN pip install --no-cache-dir ".[redis]"

# 워커 코드
WORKDIR /app
COPY examples/worker/ .

CMD ["python3", "run.py"]
